/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpg2.Ajuda;

import rpg2.Sistema.Creditos;
import rpg2.Imagens.Imagens;
import rpg2.Ficha.Status;
import rpg2.Sistema.Tela;

/**
 *
 * @author M4ESTRO
 */
public class AjudaStatusView extends javax.swing.JFrame {

    /**
     * Creates new form AjudaStatusView
     */
    public AjudaStatusView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAjuda = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaAjudaStatus = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jButtonSobreLevel = new javax.swing.JButton();
        jButtonSobreKarma = new javax.swing.JButton();
        jButtonSobreSlots = new javax.swing.JButton();
        jButtonSobreVitalidade = new javax.swing.JButton();
        jButtonSobreApetencia = new javax.swing.JButton();
        jButtonSobreEspecial = new javax.swing.JButton();
        jButtonSobreForca = new javax.swing.JButton();
        jButtonSobreStamina = new javax.swing.JButton();
        jButtonSobreResistencia = new javax.swing.JButton();
        jButtonSobrePercepcao = new javax.swing.JButton();
        jButtonSobreInteligencia = new javax.swing.JButton();
        jButtonSobrePeso = new javax.swing.JButton();
        jButtonSobreCarisma = new javax.swing.JButton();
        jButtonSobreDebuffers = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaQuadroInfo = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuVoltarJogo = new javax.swing.JMenu();
        jMenuCreditos2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AJUDA - Status");
        setIconImage(Imagens.getIconeTela(1));
        setMinimumSize(Tela.telaFull());
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanelAjuda.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAjuda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanelAjuda.setEnabled(false);
        jPanelAjuda.setPreferredSize(Tela.telaFull());

        jTextAreaAjudaStatus.setEditable(false);
        jTextAreaAjudaStatus.setColumns(20);
        jTextAreaAjudaStatus.setLineWrap(true);
        jTextAreaAjudaStatus.setRows(5);
        jTextAreaAjudaStatus.setText(Textos.getSobreStatus()
        );
        jTextAreaAjudaStatus.setWrapStyleWord(true);
        jTextAreaAjudaStatus.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));
        jScrollPane4.setViewportView(jTextAreaAjudaStatus);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Descubra mais sobre os status"));

        jButtonSobreLevel.setText("Level");
        jButtonSobreLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobreLevelActionPerformed(evt);
            }
        });

        jButtonSobreKarma.setText("Karma");
        jButtonSobreKarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobreKarmaActionPerformed(evt);
            }
        });

        jButtonSobreSlots.setText("Slots");
        jButtonSobreSlots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobreSlotsActionPerformed(evt);
            }
        });

        jButtonSobreVitalidade.setText("Vitalidade");
        jButtonSobreVitalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobreVitalidadeActionPerformed(evt);
            }
        });

        jButtonSobreApetencia.setText("Apetência");
        jButtonSobreApetencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobreApetenciaActionPerformed(evt);
            }
        });

        jButtonSobreEspecial.setText("Especial");
        jButtonSobreEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobreEspecialActionPerformed(evt);
            }
        });

        jButtonSobreForca.setText("Força");
        jButtonSobreForca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobreForcaActionPerformed(evt);
            }
        });

        jButtonSobreStamina.setText("Stamina");
        jButtonSobreStamina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobreStaminaActionPerformed(evt);
            }
        });

        jButtonSobreResistencia.setText("Resistência");
        jButtonSobreResistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobreResistenciaActionPerformed(evt);
            }
        });

        jButtonSobrePercepcao.setText("Percepção");
        jButtonSobrePercepcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobrePercepcaoActionPerformed(evt);
            }
        });

        jButtonSobreInteligencia.setText("Inteligência");
        jButtonSobreInteligencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobreInteligenciaActionPerformed(evt);
            }
        });

        jButtonSobrePeso.setText("Peso");
        jButtonSobrePeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobrePesoActionPerformed(evt);
            }
        });

        jButtonSobreCarisma.setText("Carisma");
        jButtonSobreCarisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobreCarismaActionPerformed(evt);
            }
        });

        jButtonSobreDebuffers.setText("Debuffers");
        jButtonSobreDebuffers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobreDebuffersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonSobreApetencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSobreResistencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jButtonSobreCarisma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSobreLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSobreEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSobrePercepcao, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSobreKarma, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonSobreForca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSobreSlots, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSobreInteligencia, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSobreStamina, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSobrePeso, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSobreVitalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonSobreDebuffers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSobreLevel)
                    .addComponent(jButtonSobreKarma)
                    .addComponent(jButtonSobreSlots)
                    .addComponent(jButtonSobreVitalidade))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSobreApetencia)
                    .addComponent(jButtonSobreEspecial)
                    .addComponent(jButtonSobreForca)
                    .addComponent(jButtonSobreStamina))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSobreResistencia)
                    .addComponent(jButtonSobrePercepcao)
                    .addComponent(jButtonSobreInteligencia)
                    .addComponent(jButtonSobrePeso))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSobreCarisma)
                    .addComponent(jButtonSobreDebuffers))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextAreaQuadroInfo.setEditable(false);
        jTextAreaQuadroInfo.setColumns(20);
        jTextAreaQuadroInfo.setRows(5);
        jTextAreaQuadroInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabela"));
        jScrollPane5.setViewportView(jTextAreaQuadroInfo);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg2/Imagens/BHC Soldier2.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAjudaLayout = new javax.swing.GroupLayout(jPanelAjuda);
        jPanelAjuda.setLayout(jPanelAjudaLayout);
        jPanelAjudaLayout.setHorizontalGroup(
            jPanelAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAjudaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelAjudaLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelAjudaLayout.setVerticalGroup(
            jPanelAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAjudaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelAjuda);

        jMenuVoltarJogo.setText("Voltar ao Jogo");
        jMenuVoltarJogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuVoltarJogoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuVoltarJogo);

        jMenuCreditos2.setText("Créditos");
        jMenuCreditos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCreditos2MouseClicked(evt);
            }
        });
        jMenuCreditos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCreditos2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuCreditos2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSobreLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobreLevelActionPerformed
        Status.limpaCampo(jTextAreaQuadroInfo);
        Textos.getSobreLevel();
    }//GEN-LAST:event_jButtonSobreLevelActionPerformed

    private void jButtonSobreKarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobreKarmaActionPerformed
        Status.limpaCampo(jTextAreaQuadroInfo);
        Textos.getSobreKarma();
    }//GEN-LAST:event_jButtonSobreKarmaActionPerformed

    private void jButtonSobreSlotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobreSlotsActionPerformed
        Status.limpaCampo(jTextAreaQuadroInfo);
        Textos.getSobreSlot();
    }//GEN-LAST:event_jButtonSobreSlotsActionPerformed

    private void jButtonSobreVitalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobreVitalidadeActionPerformed
        Status.limpaCampo(jTextAreaQuadroInfo);
        Textos.getSobreVitalidade();
    }//GEN-LAST:event_jButtonSobreVitalidadeActionPerformed

    private void jButtonSobreApetenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobreApetenciaActionPerformed
        Status.limpaCampo(jTextAreaQuadroInfo);
        Textos.getSobreApetencia();
    }//GEN-LAST:event_jButtonSobreApetenciaActionPerformed

    private void jButtonSobreEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobreEspecialActionPerformed
        Status.limpaCampo(jTextAreaQuadroInfo);
        Textos.getSobreEspecial();
    }//GEN-LAST:event_jButtonSobreEspecialActionPerformed

    private void jButtonSobreForcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobreForcaActionPerformed
        Textos.setQuadro(jTextAreaQuadroInfo);
        Textos.getSobreForca();
    }//GEN-LAST:event_jButtonSobreForcaActionPerformed

    private void jButtonSobreStaminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobreStaminaActionPerformed
        Textos.setQuadro(jTextAreaQuadroInfo);
        Textos.getSobreStamina();
    }//GEN-LAST:event_jButtonSobreStaminaActionPerformed

    private void jButtonSobreResistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobreResistenciaActionPerformed
        Textos.setQuadro(jTextAreaQuadroInfo);
        Textos.getSobreResistencia();
    }//GEN-LAST:event_jButtonSobreResistenciaActionPerformed

    private void jButtonSobrePercepcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobrePercepcaoActionPerformed
        Textos.setQuadro(jTextAreaQuadroInfo);
        Textos.getSobrePercepcao();
    }//GEN-LAST:event_jButtonSobrePercepcaoActionPerformed

    private void jButtonSobreInteligenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobreInteligenciaActionPerformed
        Textos.setQuadroInt(jTextAreaQuadroInfo);
        Textos.getSobreInteligencia();
    }//GEN-LAST:event_jButtonSobreInteligenciaActionPerformed

    private void jButtonSobrePesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobrePesoActionPerformed
        Textos.setQuadroPes(jTextAreaQuadroInfo);
        Textos.getSobrePeso();
    }//GEN-LAST:event_jButtonSobrePesoActionPerformed

    private void jButtonSobreCarismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobreCarismaActionPerformed
        Status.limpaCampo(jTextAreaQuadroInfo);
        Textos.getSobreCarisma();
    }//GEN-LAST:event_jButtonSobreCarismaActionPerformed

    private void jButtonSobreDebuffersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobreDebuffersActionPerformed
        Textos.setQuadroDebuffer(jTextAreaQuadroInfo);
        Textos.getSobreDebuffers();
    }//GEN-LAST:event_jButtonSobreDebuffersActionPerformed

    private void jMenuVoltarJogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuVoltarJogoMouseClicked
         this.dispose();
    }//GEN-LAST:event_jMenuVoltarJogoMouseClicked

    private void jMenuCreditos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCreditos2MouseClicked
        Creditos.creditos();
    }//GEN-LAST:event_jMenuCreditos2MouseClicked

    private void jMenuCreditos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCreditos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCreditos2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjudaStatusView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjudaStatusView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjudaStatusView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjudaStatusView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjudaStatusView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSobreApetencia;
    private javax.swing.JButton jButtonSobreCarisma;
    private javax.swing.JButton jButtonSobreDebuffers;
    private javax.swing.JButton jButtonSobreEspecial;
    private javax.swing.JButton jButtonSobreForca;
    private javax.swing.JButton jButtonSobreInteligencia;
    private javax.swing.JButton jButtonSobreKarma;
    private javax.swing.JButton jButtonSobreLevel;
    private javax.swing.JButton jButtonSobrePercepcao;
    private javax.swing.JButton jButtonSobrePeso;
    private javax.swing.JButton jButtonSobreResistencia;
    private javax.swing.JButton jButtonSobreSlots;
    private javax.swing.JButton jButtonSobreStamina;
    private javax.swing.JButton jButtonSobreVitalidade;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCreditos2;
    private javax.swing.JMenu jMenuVoltarJogo;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelAjuda;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextAreaAjudaStatus;
    private javax.swing.JTextArea jTextAreaQuadroInfo;
    // End of variables declaration//GEN-END:variables
}
