/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpg2.Ajuda;

import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import rpg2.ArmasItens.Equipamentos;
import rpg2.Sistema.Creditos;
import rpg2.Sistema.FundoTelas;
import rpg2.Imagens.Imagens;
import rpg2.Sistema.Tela;

/**
 *
 * @author M4ESTRO
 */
public class HistoriaView extends javax.swing.JFrame {

    String senhaFinal = "Nathy";
    boolean autenticador = false;

    /**
     * Creates new form HistoriaView
     */
    public HistoriaView() {
        initComponents();
    }

    public static void setFinalTrue() {
        jTextAreaFinal.setText("O jogo possui quatro finais:\n"
                + "Bom: Se a média do karma do grupo for maior ou igual a 70\n"
                + "- O Hunter aparece para ajudar no combate\n"
                + "- O grupo consegue com a ajuda do Hunter e do exército derrotar a besta.\n"
                + "- Após o combate, o grupo ruma para conflitar o homem misterioso na igreja destruída. Por sua vez o homem causa uma explosão no local.\n"
                + "Epílogo: O grupo é salvo por outro homem misterioso que revela ser o arcanjo Miguel. Miguel por sua vez diz ao grupo que precisará de sua ajuda, afinal, aquilo era apenas o início.\n"
                + "\n"
                + "Mais ou Menos BOM: Se a média do karma for menor que 70 e maior ou igual a 30\n"
                + "- O Hunter não aparece para ajudar no combate\n"
                + "- O grupo derrota parcialmente a criatura, por sua vez o exército pede o lançamento de um míssel nuclear.\n"
                + "- Após o combate o grupo tenta fugir de helicóptero, mas o Hunter aparece. O jogador com menor Karma se sacrificará para segurar o Hunter enquanto o resto foge.\n"
                + "Epílogo: O grupo foge ainda lamentando sua perda, por sua vez, eles sabem que aquilo não termina ali.\n"
                + "\n"
                + "Mais ou Menos RUIM: Se a média do karma for menor que 30\n"
                + "- O Hunter não aparece para ajudar, além disso, a besta fica ainda mais forte por conta do grupo ter o karma baixo.\n"
                + "- O grupo derrota parcialmente a criatura e quando vai fugir o Hunter aparece destruindo o helicoptero e prendendo todos ali com ele.\n"
                + "- O grupo morre em combate.\n"
                + "Epílogo: O general James faz um discurso falando sobre as bravas vidas sacrificadas para impedir o pior. Motivando ainda mais os novos recrutas da B.H.C.\n"
                + "\n"
                + "Péssimo: Se o grupo falhar em matar a besta\n"
                + "- O grupo inteiro morre e de forma definitiva\n"
                + "- A besta demoniáca junto a Bathomet destrói a cidade.\n"
                + "Epílogo: O inferno se abre na terra, é definitivamente o fim...");
    }

    public static void setFinalFalse() {
        jTextAreaFinal.setText("Faça login no MMS para ler os finais");
    }

    public static void acessoConteudo(boolean autenticador) {
        if (autenticador) {
            setFinalTrue();
        } else {
            setFinalFalse();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelHistoria = new FundoTelas(22);
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPaneHist = new javax.swing.JEditorPane();
        jPanelGameplay = new FundoTelas(22);
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jPanelSistemaXP = new FundoTelas(22);
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jPanelHistoriaJogador = new FundoTelas(22);
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jPanelSistemaCombate = new FundoTelas(22);
        jLabel5 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jPanelPontosSeguros = new FundoTelas(22);
        jLabel6 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jPanelCapitulos = new FundoTelas(22);
        jLabel7 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jPanelExo = new FundoTelas(22);
        jLabel8 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jPanelSistemaMorte = new FundoTelas(22);
        jLabel9 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jPanelPericia = new FundoTelas(22);
        jLabel10 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jScrollPaneConstrucao = new javax.swing.JScrollPane();
        jPanel1 = new FundoTelas(22);
        jLabel13 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextAreaAtiv1 = new javax.swing.JTextArea();
        jComboBoxComp = new javax.swing.JComboBox<>();
        jLabelComp = new javax.swing.JLabel();
        jTextFieldCompNome = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPaneCompDesc = new javax.swing.JEditorPane();
        jPanelAtiv = new FundoTelas(15);
        jLabel12 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextAreaAtiv = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jPanelFinal = new FundoTelas(15);
        jLabel11 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextAreaFinal = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuVoltar = new javax.swing.JMenu();
        jMenuCreditos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AJUDA - História & Gameplay");
        setIconImage(Imagens.getIconeTela(1));
        setMinimumSize(Tela.telaFull());
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("História: ");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg2/Imagens/Soldados ao chao.png"))); // NOI18N

        jEditorPaneHist.setContentType("text/html");
        jEditorPaneHist.setEditable(false);
        jEditorPaneHist.setText("Narrando a história de sobreviventes de um surto viral, <b>The Unreal System project</b> se passa no ano 2022 nas cidades fictícia de <b><font color = \"red\"> Luisidiana(metrópole) </font> e<font color = \"#D39600\">  Kranch(interior) </font></b>na Polônia. <br>\nA empresa Unreal System’s Technologies, a maior empresa de sistemas computacionais, aparelhos eletrônicos, drogas farmacêutica e equipamento bélico, parece ser a principal responsável pelo surto viral ocorrido na cidade de Luisidiana (Polônia), enquanto por algum motivo a maioria esmagadora das forças militares mundiais fecham os olhos para o acontecido, a força mercenária da B.H.C envia seus homens para a cidade em busca de evidências do ocorrido e que possa comprovar a culpa da Unreal System, junto aos governos mundiais.<br>\nA verdade é que há muitos fatos desconhecidos ainda, tanto sobre o surto viral, quanto sobre a própria Unreal.<br>\nA Unreal por sua vez, despacha seu próprio (e claro, não oficial) exército mercenário para exterminar de vez as provas, juntamente com as testemunhas do ocorrido.<br> \nDuas semanas após o surto, um grupo de sobrevivente deve lutar para continuar vivo na cidade de Luisidiana, enfrentando criminosos sádicos, terroristas fanáticos, os terríveis infectados (ou mutantes) e até mesmo a própria força tática da Unreal. <br>");
        jScrollPane1.setViewportView(jEditorPaneHist);

        javax.swing.GroupLayout jPanelHistoriaLayout = new javax.swing.GroupLayout(jPanelHistoria);
        jPanelHistoria.setLayout(jPanelHistoriaLayout);
        jPanelHistoriaLayout.setHorizontalGroup(
            jPanelHistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoriaLayout.createSequentialGroup()
                .addGroup(jPanelHistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHistoriaLayout.createSequentialGroup()
                        .addGroup(jPanelHistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelHistoriaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(jPanelHistoriaLayout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 861, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelHistoriaLayout.setVerticalGroup(
            jPanelHistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 511, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("História", jPanelHistoria);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gameplay: ");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Com uma gameplay limitada, só é possível mestrar para no máximo dois grupos simultâneos, sendo um grupo de cada vez com cada grupo pegando missões diferentes. Ao final cada grupo tem seu próprio final baseado em suas escolhas durante a gameplay.\nA um total de quatro finais possíveis, e cada grupo ode obter apenas um final.\nCada grupo é composto por 4 membros, sendo cada um de uma classe diferente, não podendo haver classes repetidas por grupo.\n\nNo jogo todas as classes podem: Correr, pular, agachar, atirar de cobertura, lutar, usar armas de fogo, pilotar veículos terrestres e aéreos, escalar e executar movimentos básicos de parkour.\nÉ possível combater inimigos usando ataques físicos, com armas de fogo, montando armadilhas e em steath.\n\nPara atacar se usa o dado proporcional à sua FORÇA.\nPara defender-se, assim como executar uma fuga (corrida) usa-se o dado proporcional à sua STAMINA.\nPara eventos de QTE (Quick Time Event) e testes de resistência (especialmente usado no parkour), usa-se o dado proporcional à sua RESISTÊNCIA.\nPara defesa em steath, detectar ações contextuais e inimigos, usa-se o dado proporcional à sua PERCEPÇÃO. \n* verifique o menu de ajuda com status para mais informação.\n\nDurante a sobrevivência na cidade de Luisidiana, o grupo precisará se alimentar, embora não seja muito difícil arrumar alimentos. \n* verifique o menu de ajuda com status para mais informação.\n\nFuturamente há o uso de Exo-esqueleto de combates.\n");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane3.setViewportView(jTextArea1);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg2/Imagens/Soldados ao chao.png"))); // NOI18N

        javax.swing.GroupLayout jPanelGameplayLayout = new javax.swing.GroupLayout(jPanelGameplay);
        jPanelGameplay.setLayout(jPanelGameplayLayout);
        jPanelGameplayLayout.setHorizontalGroup(
            jPanelGameplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGameplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGameplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGameplayLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane3))
                    .addGroup(jPanelGameplayLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelGameplayLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(875, Short.MAX_VALUE))
        );
        jPanelGameplayLayout.setVerticalGroup(
            jPanelGameplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGameplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Gameplay", jPanelGameplay);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sistema de XP:");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Conforme mata inimigos e completa missões, o grupo vai adquirindo XP até upar.\nO XP só fica acumulado até upar, após upar o XP que sobraria é zerado novamente.\nA cada nível o player ganha uma skill point que pode ser gasta como ele desejar.\nCada nível sobe em 100 o XP necessário para upar, por exemplo:\nNível 1 – 100 xp.\nNível 2 – 200 xp.\nNível 3 – 300 xp.\n...\n");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane5.setViewportView(jTextArea2);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg2/Imagens/Soldados ao chao.png"))); // NOI18N

        javax.swing.GroupLayout jPanelSistemaXPLayout = new javax.swing.GroupLayout(jPanelSistemaXP);
        jPanelSistemaXP.setLayout(jPanelSistemaXPLayout);
        jPanelSistemaXPLayout.setHorizontalGroup(
            jPanelSistemaXPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSistemaXPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSistemaXPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSistemaXPLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1892, Short.MAX_VALUE))
                    .addGroup(jPanelSistemaXPLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelSistemaXPLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSistemaXPLayout.setVerticalGroup(
            jPanelSistemaXPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSistemaXPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 498, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Sistema de XP", jPanelSistemaXP);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("História dos jogadores: ");

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Cada player PRECISA escrever sua história do passado, assim como a história do que aconteceu com seu personagem durante as duas semanas entre o prólogo e o encontro do grupo.\nTambém precisa dizer PELO MENOS três grandes medos que o personagem tem, e PELO MENOS uma coisa da qual se envergonha muito de ter feito em seu passado. Isso tudo é necessário no decorrer da história. \n*Tudo isso é OBRIGATÓRIO, e deve ser anotado no campo da ficha: “Anotações & Perícias”.\n**Eu enquanto mestre, costumo recompensar boas histórias e desenvolvimento do personagem. Normalmente dou XP adicional, itens básicos e até skill point (se a história, medos e etc que a pessoa escreveu for extremamente boa e bem feita é claro).\n");
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane6.setViewportView(jTextArea3);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg2/Imagens/Soldados ao chao.png"))); // NOI18N

        javax.swing.GroupLayout jPanelHistoriaJogadorLayout = new javax.swing.GroupLayout(jPanelHistoriaJogador);
        jPanelHistoriaJogador.setLayout(jPanelHistoriaJogadorLayout);
        jPanelHistoriaJogadorLayout.setHorizontalGroup(
            jPanelHistoriaJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoriaJogadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHistoriaJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHistoriaJogadorLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1892, Short.MAX_VALUE))
                    .addGroup(jPanelHistoriaJogadorLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelHistoriaJogadorLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHistoriaJogadorLayout.setVerticalGroup(
            jPanelHistoriaJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoriaJogadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 506, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("História dos jogadores", jPanelHistoriaJogador);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sistema de Combate:");

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("O combate é definido por turnos, deve-se jogar um D20, e os que forem tirando o maior número começam, caso alguém tire um dado igual ao de um inimigo HUMANO, eles devem jogar novamente apenas para desempatar, caso seja igual a um inimigo INFECTADO, o player joga primeiro. Vale lembrar, o BOSS sempre joga primeiro!\nDurante o combate existe questões táticas como cobertura (que em sua grande maioria são destruíveis), distância e ações contextuais.\nA cobertura serve principalmente contra inimigos humanos e te ajuda a se proteger, mesmo que se tome dano estando em cobertura, ele será menor do que fora dela.\nA distância de até onde o tiro pode ir (ou até onde sua visão alcança), e a distância de um inimigo até você e vice-versa, inimigos infectados em sua maioria precisam estar perto para atacar um player. Caso a distância seja grande, o inimigo perderá o turno para alcançar o player.\nAções contextuais, são ações únicas ou especificas de cada ação ou classe respectivamente. Por exemplo: uma ação contextual única ocorre quando os players conflitam o Homem misterioso. Já uma ação especifica de classe, ocorre quando por exemplo, um Hacker altera o ambiente atual, descendo uma plataforma, subindo uma ponte, estourando um bueiro ou rede elétrica.\n");
        jTextArea4.setWrapStyleWord(true);
        jTextArea4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane7.setViewportView(jTextArea4);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg2/Imagens/Soldados ao chao.png"))); // NOI18N

        javax.swing.GroupLayout jPanelSistemaCombateLayout = new javax.swing.GroupLayout(jPanelSistemaCombate);
        jPanelSistemaCombate.setLayout(jPanelSistemaCombateLayout);
        jPanelSistemaCombateLayout.setHorizontalGroup(
            jPanelSistemaCombateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSistemaCombateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSistemaCombateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSistemaCombateLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1892, Short.MAX_VALUE))
                    .addGroup(jPanelSistemaCombateLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelSistemaCombateLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSistemaCombateLayout.setVerticalGroup(
            jPanelSistemaCombateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSistemaCombateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 444, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Sistema de Combate", jPanelSistemaCombate);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pontos seguros");

        jTextArea5.setEditable(false);
        jTextArea5.setColumns(20);
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.setText("Locais seguros podem ser encontrados ao redor de todo o mapa de Luisidiana, Kranch e na zona florestal. Alguns destes pontos precisam ser recuperados de criminosos, terroristas, infectados ou agentes da Unreal, antes de serem de fato “seguros”.\nHá também assentamentos aliados espalhados pelos mapas de Luisidiana e Kranch, todos servem como pontos seguros, há também a principal cidadela do jogo Roma.\n\nRoma e assentamentos aliados podem ser atacados a qualquer momento, ajudar a defende-los em alguns casos é opcional e em outros obrigatórios, ajudar com sucesso sempre trará boas recompensas.\nEm Roma e em qualquer assentamento aliado, pode-se comprar itens, equipamentos e alimentos.\n\nHá também assentamentos inimigos (comandada por criminosos), bases de operações terroristas e laboratórios auxiliares da Unreal. Todos esses contam como atividades secundárias e após limpo passam a ser zonas seguras ou assentamentos aliados.\n");
        jTextArea5.setWrapStyleWord(true);
        jTextArea5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane8.setViewportView(jTextArea5);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg2/Imagens/Soldados ao chao.png"))); // NOI18N

        javax.swing.GroupLayout jPanelPontosSegurosLayout = new javax.swing.GroupLayout(jPanelPontosSeguros);
        jPanelPontosSeguros.setLayout(jPanelPontosSegurosLayout);
        jPanelPontosSegurosLayout.setHorizontalGroup(
            jPanelPontosSegurosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPontosSegurosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPontosSegurosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPontosSegurosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 1892, Short.MAX_VALUE))
                    .addGroup(jPanelPontosSegurosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelPontosSegurosLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPontosSegurosLayout.setVerticalGroup(
            jPanelPontosSegurosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPontosSegurosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 442, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Pontos seguros", jPanelPontosSeguros);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Capítulos");

        jTextArea6.setEditable(false);
        jTextArea6.setColumns(20);
        jTextArea6.setLineWrap(true);
        jTextArea6.setRows(5);
        jTextArea6.setText("O jogo contém 6 capítulos.\nCada capítulo com exceção do último contém 15 missões principais e 10 missões secundárias.\nHá também as atividades secundárias que servem para complementar a gameplay e cujo também dão recompensas.\nAlém disso há um gerador aleatório de eventos que pode ser usado para criar eventos rápidos e dinâmicos.\n*O último capítulo contém apenas 3 missões principais.\n");
        jTextArea6.setWrapStyleWord(true);
        jTextArea6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane9.setViewportView(jTextArea6);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg2/Imagens/Soldados ao chao.png"))); // NOI18N

        javax.swing.GroupLayout jPanelCapitulosLayout = new javax.swing.GroupLayout(jPanelCapitulos);
        jPanelCapitulos.setLayout(jPanelCapitulosLayout);
        jPanelCapitulosLayout.setHorizontalGroup(
            jPanelCapitulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCapitulosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCapitulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCapitulosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 1892, Short.MAX_VALUE))
                    .addGroup(jPanelCapitulosLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelCapitulosLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCapitulosLayout.setVerticalGroup(
            jPanelCapitulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCapitulosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 534, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Capítulos", jPanelCapitulos);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Exo-Esqueleto de combate");

        jTextArea7.setEditable(false);
        jTextArea7.setColumns(20);
        jTextArea7.setLineWrap(true);
        jTextArea7.setRows(5);
        jTextArea7.setText("Os exo-esqueletos de combates podem e devem ser usado por todas as classes, ele melhora sua movimentação em tudo, pular, correr, parkour (principalmente), além de aumentar sua defesa.");
        jTextArea7.setWrapStyleWord(true);
        jTextArea7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane10.setViewportView(jTextArea7);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg2/Imagens/Soldados ao chao.png"))); // NOI18N

        javax.swing.GroupLayout jPanelExoLayout = new javax.swing.GroupLayout(jPanelExo);
        jPanelExo.setLayout(jPanelExoLayout);
        jPanelExoLayout.setHorizontalGroup(
            jPanelExoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelExoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelExoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 1892, Short.MAX_VALUE))
                    .addGroup(jPanelExoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelExoLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelExoLayout.setVerticalGroup(
            jPanelExoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 542, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Exo-Esqueleto", jPanelExo);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sistema de Morte");

        jTextArea8.setEditable(false);
        jTextArea8.setColumns(20);
        jTextArea8.setLineWrap(true);
        jTextArea8.setRows(5);
        jTextArea8.setText("Caso um player venha a ser cercado por uma hora de inimigos, o mesmo tem três rodadas para ser resgatado, do contrário é morte instantaneamente.\nPlayers com VITALIDADE zerada tem três rodadas para ser revivido por outro player, do contrário ele também morre.\nExceto mortes específicas ou causadas por um inimigo específico é permanente, do contrário o player morte vai parar no “Inferno pessoal”, onde seus aliados terão que enfrentar seus maiores medo para poder resgata-lo. Para ir ao inferno pessoal de alguém resgata-lo, o grupo precisa ir até a igreja Nova Vida para iniciar o ritual.\nPlayer resgatado do Inferno pessoal perde todos os seus itens (recomeçando apenas com o default de sua classe).\nPlayer morto definitivamente pode recomeçar com um novo personagem de classe. O recomeço é com o menor nível do grupo atual, por exemplo:\nHá um grupo com dois players nível 25, um player nível 20 e um player nível 30. Se o player nível 30 morrer permanentemente, ele poderá recomeçar com uma nova ficha a partir do nível 20.\nCaso todos os players morram, o jogo acaba.\n");
        jTextArea8.setWrapStyleWord(true);
        jTextArea8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane11.setViewportView(jTextArea8);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg2/Imagens/Soldados ao chao.png"))); // NOI18N

        javax.swing.GroupLayout jPanelSistemaMorteLayout = new javax.swing.GroupLayout(jPanelSistemaMorte);
        jPanelSistemaMorte.setLayout(jPanelSistemaMorteLayout);
        jPanelSistemaMorteLayout.setHorizontalGroup(
            jPanelSistemaMorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSistemaMorteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSistemaMorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSistemaMorteLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 1892, Short.MAX_VALUE))
                    .addGroup(jPanelSistemaMorteLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelSistemaMorteLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSistemaMorteLayout.setVerticalGroup(
            jPanelSistemaMorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSistemaMorteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 449, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Sistema de Morte", jPanelSistemaMorte);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Perícias: ");

        jTextArea9.setEditable(false);
        jTextArea9.setColumns(20);
        jTextArea9.setLineWrap(true);
        jTextArea9.setRows(5);
        jTextArea9.setText("As perícias são complementos de habilidades que geram vantagens para certas ações de um personagem dentro de um contexto, elas são adquiridas ao alcançar os níveis 5, 10, 15  e 20, podendo-se optar em cada nível por uma perícia, com isso, claramente cada personagem pode ter no máximo 4 perícias.\n\n\nPerícia\t\tDescrição\n\n\nPistolas\t\tRemove uma desvantagens no dado ao usar pistolas. [APENAS CLASSES CIVIS]\nSubmetralhadoras\tRemove uma desvantagens no dado ao usar submetralhadoras. [APENAS CLASSES CIVIS]\nFuzis\t\tRemove uma desvantagens no dado ao usar fuzis. [APENAS CLASSES CIVIS]\nEscopetas\t\tRemove uma desvantagens no dado ao usar escopetas. [APENAS CLASSES CIVIS]\nSniper\t\tRemove uma desvantagens no dado ao usar sniper. [APENAS CLASSES CIVIS]\nMagnum\t\tRemove uma desvantagens no dado ao usar magnum. [APENAS CLASSES CIVIS]\nEspecial\t\tPermite a utilização de equipamento especial. [APENAS CLASSES MILITARES].\nArrombamento\t\tPermite realizar arrombamentos em cadeados e portas simples.\nDireção\t\tRemove a desvantagens no dado para direção de veículo terrestre\nVeículo terrestre\tCede um de vantagem no dado para direção de veículo terrestre. [É NECESSÁRIO POSSUIR A PERÍCA DIREÇÃO].\nPilotagem\t\tRemove a desvantagens no dado para pilotagem de veículo aéreos\nVeículo Aéreo\t\tCede um de vantagem no dado para pilotagem de veículo aéreo. [É NECESSÁRIO POSSUIR A PERÍCA PILOTAGEM].\nNegociação\t\tConcede 10% de desconto com os vendedores\nSobrevivência\t\tPermite que caia de alturas maiores sem sofrer tanto dano, além de restaurar +5 de vitalidade ao consumir alimentos\nEscalada\t\tRemove uma desvantagens no dado, ou cede uma vantagem no dado para escaladas\nEquilíbrio\t\tRemove uma desvantagens no dado, ou cede uma vantagem no dado para equilíbrio\nVida\t\tCaso teu HP caia abaixo de ZERO com um ataque, ele cairá na verdade para UM (isso só pode acontecer uma vez por batalha).\nCoragem\t\tImunidade ao medo.\nCoração\t\tConcede um dano bónus de +5 quando a VITALIDADE cai abaixo de 50%\nBusca\t\tGanha munição extra ao vasculhar contêineres e baús.");
        jTextArea9.setWrapStyleWord(true);
        jTextArea9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane12.setViewportView(jTextArea9);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg2/Imagens/Soldados ao chao.png"))); // NOI18N

        javax.swing.GroupLayout jPanelPericiaLayout = new javax.swing.GroupLayout(jPanelPericia);
        jPanelPericia.setLayout(jPanelPericiaLayout);
        jPanelPericiaLayout.setHorizontalGroup(
            jPanelPericiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPericiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPericiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPericiaLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 1892, Short.MAX_VALUE))
                    .addGroup(jPanelPericiaLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelPericiaLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPericiaLayout.setVerticalGroup(
            jPanelPericiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPericiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Perícias", jPanelPericia);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Sistema de Construção");

        jTextAreaAtiv1.setEditable(false);
        jTextAreaAtiv1.setColumns(20);
        jTextAreaAtiv1.setLineWrap(true);
        jTextAreaAtiv1.setRows(5);
        jTextAreaAtiv1.setText("No RPG é possível encontrar, comprar e utilizar componentes de construções para criar itens e equipamentos.\nHá quatro tipos de componentes de construção que podem ser encontrados:\nComponente de construção, utilizado únicamente por engenheiros;\nComponente químico-hospitalar, utilizado por médicos e em um único caso, químicos;\nComponente químico-explosivo, utilizado por químicos;\nComponente eletrónico de hackeamento, utilizado por hackers.\nTodos os componentes são usados por engenheiros. \nNo geral, componenentes de construção são usados para construir armas brancas, acessórios para armas de fogo e mods para armas brancas, além de barricadas e outras coisas. Componenentes químico-hospitalar são usados para criar itens de cura, componenetes químico-explosivo são usados para criar bombas e outros itens explosivos, além de munição especial para a Lançadora-Química. E por fim o componenete eletrónico de hackeamento são usados para criar exploits hacker.\n\nUtilize a caixa de combinação abaixo para descobrir os possíveis itens a serem construídos por esses componenentes.\n\n");
        jTextAreaAtiv1.setWrapStyleWord(true);
        jTextAreaAtiv1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane15.setViewportView(jTextAreaAtiv1);

        jComboBoxComp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o componenente", "Componenente de Construção", "Componenente Químico-explosivo", "Componenente Químico-hospitalar", "Componenente Eletrónico de hackeamento" }));
        jComboBoxComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCompActionPerformed(evt);
            }
        });

        jLabelComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg2/Imagens/CDEFAULT.png"))); // NOI18N
        jLabelComp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelComp.setMaximumSize(new java.awt.Dimension(300, 300));
        jLabelComp.setMinimumSize(new java.awt.Dimension(300, 300));
        jLabelComp.setPreferredSize(new java.awt.Dimension(300, 300));

        jTextFieldCompNome.setEditable(false);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg2/Imagens/Soldados ao chao.png"))); // NOI18N

        jEditorPaneCompDesc.setEditable(false);
        jScrollPane4.setViewportView(jEditorPaneCompDesc);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxComp, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelComp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCompNome, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 907, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldCompNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPaneConstrucao.setViewportView(jPanel1);

        jTabbedPane1.addTab("Sistema de Construção", jScrollPaneConstrucao);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Atividades secundárias:");

        jTextAreaAtiv.setEditable(false);
        jTextAreaAtiv.setColumns(20);
        jTextAreaAtiv.setLineWrap(true);
        jTextAreaAtiv.setRows(5);
        jTextAreaAtiv.setText("O RPG possui cerca de 10 atividades secundárias,cujo, não só contabilizam para completude do jogo, como fornece informações e recompensas extras, elas podem ser encontradas ao redor de todo o mapa (e em todos os mapas com exceção do Laboratório Geral da Unreal).\nAlém disso o RPG conta com um gerador aleatório(ou não) de eventos para dar mais vida, imersão e dinamismo à gameplay, os eventos vão desde:\nAjudar um assentamento aliado, à buscar suprimento em um local, sendo possível acessar mais de 15 eventos diferentes.\n\nAs atividades secundárias são:\n\nNome da atividade\tDescrição\t\t\t\t\t\t\t\t\t\nRetomada.\t\tTomar assentamentos inimigos.\t\t\t\t\t\t\t\nServiço de escolta.\tEscoltar veículos, pessoa ou grupo de pessoa.\t\t\t\t\t\t\t\t\nReconectando.\t\tEstabelecer conexão com a B.H.C montando receptores em locais estratégicos.\t\nAuxiliares do capeta.\tDestruir laboratórios auxiliares da Unreal. - [Após o capítulo um apenas]\t\nGuerra ao terror.\tTomar base de operações terroristas.\t\nSelamento.\t\tBuracos infernais para serem destruídos - [Após o capítulo dois apenas].\t\nDesestabilização.\tEntradas para as rupturas - [Após o capitulo dois apenas].\t\nSem paz.\t\tLibertar almas do tormento da dor - [Após o capitulo dois apenas].\t\nSem luz.\t\tLiberar luz no inferno da solidão - [Após o capitulo dois apenas].\t\nExtinção.\t\tCaçar as Bocejos liberadas Unreal - [Após o capítulo três].\t\n");
        jTextAreaAtiv.setWrapStyleWord(true);
        jTextAreaAtiv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane14.setViewportView(jTextAreaAtiv);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg2/Imagens/Soldados ao chao.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAtivLayout = new javax.swing.GroupLayout(jPanelAtiv);
        jPanelAtiv.setLayout(jPanelAtivLayout);
        jPanelAtivLayout.setHorizontalGroup(
            jPanelAtivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtivLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAtivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAtivLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 1892, Short.MAX_VALUE))
                    .addGroup(jPanelAtivLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 1650, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelAtivLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAtivLayout.setVerticalGroup(
            jPanelAtivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtivLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Atividades Secundárias", jPanelAtiv);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Final do jogo: ");

        jTextAreaFinal.setEditable(false);
        jTextAreaFinal.setColumns(20);
        jTextAreaFinal.setLineWrap(true);
        jTextAreaFinal.setRows(5);
        jTextAreaFinal.setText("Faça login no MMS para ler os finais");
        jTextAreaFinal.setWrapStyleWord(true);
        jTextAreaFinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane13.setViewportView(jTextAreaFinal);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg2/Imagens/Soldados ao chao.png"))); // NOI18N

        javax.swing.GroupLayout jPanelFinalLayout = new javax.swing.GroupLayout(jPanelFinal);
        jPanelFinal.setLayout(jPanelFinalLayout);
        jPanelFinalLayout.setHorizontalGroup(
            jPanelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFinalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFinalLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 1892, Short.MAX_VALUE))
                    .addGroup(jPanelFinalLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 1744, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelFinalLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFinalLayout.setVerticalGroup(
            jPanelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFinalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("O Final", jPanelFinal);

        getContentPane().add(jTabbedPane1);

        jMenuVoltar.setText("Voltar ao jogo");
        jMenuVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuVoltarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuVoltar);

        jMenuCreditos.setText("Créditos");
        jMenuCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCreditosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCreditos);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_jMenuVoltarMouseClicked

    private void jMenuCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCreditosMouseClicked
        Creditos.creditos();
    }//GEN-LAST:event_jMenuCreditosMouseClicked

    private void jComboBoxCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCompActionPerformed
        JTextArea marreta = new JTextArea();
        Componente.getComponente(jComboBoxComp, jTextFieldCompNome, marreta, jEditorPaneCompDesc, jLabelComp);
    }//GEN-LAST:event_jComboBoxCompActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoriaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoriaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoriaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoriaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoriaView().setVisible(true);
            }
        });
    }
//<editor-fold defaultstate="collapsed" desc=" cod">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxComp;
    private javax.swing.JEditorPane jEditorPaneCompDesc;
    private javax.swing.JEditorPane jEditorPaneHist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelComp;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCreditos;
    private javax.swing.JMenu jMenuVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAtiv;
    private javax.swing.JPanel jPanelCapitulos;
    private javax.swing.JPanel jPanelExo;
    private javax.swing.JPanel jPanelFinal;
    private javax.swing.JPanel jPanelGameplay;
    private javax.swing.JPanel jPanelHistoria;
    private javax.swing.JPanel jPanelHistoriaJogador;
    private javax.swing.JPanel jPanelPericia;
    private javax.swing.JPanel jPanelPontosSeguros;
    private javax.swing.JPanel jPanelSistemaCombate;
    private javax.swing.JPanel jPanelSistemaMorte;
    private javax.swing.JPanel jPanelSistemaXP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JScrollPane jScrollPaneConstrucao;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private static javax.swing.JTextArea jTextAreaAtiv;
    private static javax.swing.JTextArea jTextAreaAtiv1;
    private static javax.swing.JTextArea jTextAreaFinal;
    private javax.swing.JTextField jTextFieldCompNome;
    // End of variables declaration//GEN-END:variables
}
//</editor-fold>
