/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpg2.Ajuda;

import rpg2.Sistema.Creditos;
import rpg2.Sistema.FundoTelas;
import rpg2.Imagens.Imagens;
import rpg2.Sistema.Tela;

/**
 *
 * @author M4ESTRO
 */
public class NPCView extends javax.swing.JFrame {

    /**
     * Creates new form NPCView
     */
    public NPCView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FundoTelas(25);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSobre = new javax.swing.JTextArea();
        jComboBoxListaNPC = new javax.swing.JComboBox<>();
        jLabelImagem = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDesc = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuVoltar = new javax.swing.JMenu();
        jMenuCreditos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AJUDA - NPC's");
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImage(Imagens.getIconeTela(1));
        setMinimumSize(Tela.telaFull());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(Tela.telaFull());
        jPanel1.setMinimumSize(Tela.telaFull());
        jPanel1.setPreferredSize(Tela.telaFull());

        jTextAreaSobre.setEditable(false);
        jTextAreaSobre.setColumns(20);
        jTextAreaSobre.setLineWrap(true);
        jTextAreaSobre.setRows(5);
        jTextAreaSobre.setText("Esta presente lista possui cerca de 11 NPC's, todos de extrema importância para o jogo e sua história.\nDescubra um pouco sobre cada NPC e sua história.\nPS: Ainda falta alguns. ");
        jTextAreaSobre.setWrapStyleWord(true);
        jTextAreaSobre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(jTextAreaSobre);

        jComboBoxListaNPC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um NPC", "General James Bianco", "César", "Major Luke", "Tenente Katie", "Marcelle", "Suzie", "Rodrigo", "Clara Turner", "Lilian Turner", "Marcus Turner", "Homem Misterioso", "Homem Misterioso (ver 2)", "Homem Misterioso (ver 3)", "Lúcifer" }));
        jComboBoxListaNPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxListaNPCActionPerformed(evt);
            }
        });

        jLabelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg2/Imagens/deafultNPC.jpg"))); // NOI18N
        jLabelImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jTextAreaDesc.setEditable(false);
        jTextAreaDesc.setColumns(20);
        jTextAreaDesc.setLineWrap(true);
        jTextAreaDesc.setRows(5);
        jTextAreaDesc.setWrapStyleWord(true);
        jTextAreaDesc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane2.setViewportView(jTextAreaDesc);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sobre: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jComboBoxListaNPC, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxListaNPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImagem)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jMenuVoltar.setText("Voltar  ao jogo");
        jMenuVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuVoltarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuVoltar);

        jMenuCreditos.setText("Créditos");
        jMenuCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCreditosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCreditos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCreditosMouseClicked
        Creditos.creditos();
    }//GEN-LAST:event_jMenuCreditosMouseClicked

    private void jMenuVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_jMenuVoltarMouseClicked

    private void jComboBoxListaNPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxListaNPCActionPerformed
        int opcao = jComboBoxListaNPC.getSelectedIndex();

        switch (opcao) {
            case 1:
                NPC.getGeneralJames(jTextAreaDesc);
                NPC.setImagem(jLabelImagem, opcao);

                break;

            case 2:
                NPC.getCesar(jTextAreaDesc);
                NPC.setImagem(jLabelImagem, opcao);

                break;

            case 3:
                NPC.getMajorLuke(jTextAreaDesc);
                NPC.setImagem(jLabelImagem, opcao);

                break;

            case 4:
                NPC.getTenenteKatie(jTextAreaDesc);
                NPC.setImagem(jLabelImagem, opcao);

                break;

            case 5:
                NPC.getMarcelle(jTextAreaDesc);
                NPC.setImagem(jLabelImagem, opcao);

                break;

            case 6:
                NPC.getSuzie(jTextAreaDesc);
                NPC.setImagem(jLabelImagem, opcao);

                break;

            case 7:
                NPC.getRodrigo(jTextAreaDesc);
                NPC.setImagem(jLabelImagem, opcao);

                break;

            case 8:
                NPC.getClaraTurner(jTextAreaDesc);
                NPC.setImagem(jLabelImagem, opcao);

                break;

            case 9:
                NPC.getLilianTurner(jTextAreaDesc);
                NPC.setImagem(jLabelImagem, opcao);

                break;

            case 10:
                NPC.getMarcusTurner(jTextAreaDesc);
                NPC.setImagem(jLabelImagem, opcao);

                break;

            case 11:
                NPC.getHomemMisterioso(jTextAreaDesc);
                NPC.setImagem(jLabelImagem, opcao);

                break;
                
            case 12:
                NPC.getHomemMisterioso2(jTextAreaDesc);
                NPC.setImagem(jLabelImagem, opcao);

                break;
                
            case 13:
                NPC.getHomemMisterioso3(jTextAreaDesc);
                NPC.setImagem(jLabelImagem, opcao);

                break;   
                
                case 14:
                NPC.getLucifer(jTextAreaDesc);
                NPC.setImagem(jLabelImagem, opcao);

                break;   

            default:
                NPC.cleanDesc(jTextAreaDesc);
                NPC.setImagem(jLabelImagem, opcao);
        }
    }//GEN-LAST:event_jComboBoxListaNPCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NPCView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NPCView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NPCView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NPCView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NPCView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxListaNPC;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCreditos;
    private javax.swing.JMenu jMenuVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaDesc;
    private javax.swing.JTextArea jTextAreaSobre;
    // End of variables declaration//GEN-END:variables
}
