/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpg2.Ajuda;

import rpg2.Sistema.Creditos;
import rpg2.Sistema.FundoTelas;
import rpg2.Imagens.Imagens;
import rpg2.Sistema.Tela;

/**
 *
 * @author M4ESTRO
 */
public class VeiculoView extends javax.swing.JFrame {

    /**
     * Creates new form VeiculoView
     */
    public VeiculoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FundoTelas(29);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSobre = new javax.swing.JTextArea();
        jLabelImagem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDesc = new javax.swing.JTextArea();
        jComboBoxListaVeiculos = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuVoltar = new javax.swing.JMenu();
        jMenuCredito = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AJUDA - Veículos");
        setIconImage(Imagens.getIconeTela(1));
        setMinimumSize(Tela.telaFull());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextAreaSobre.setEditable(false);
        jTextAreaSobre.setColumns(20);
        jTextAreaSobre.setLineWrap(true);
        jTextAreaSobre.setRows(5);
        jTextAreaSobre.setText("A presente lista de veículos disponíveis, contabiliza 8 veículos no total, sendo os \"Carros civis\" e \"Carros civis esportivos\" mais um conceito do que um veículo concreto.\nTodos os carros possuem limitações físicas normais,por exemplo, você não vai conseguir dirigir um Fusca em uma floresta muito bem, para isso você precisaria de uma 4X4.\n\nCada carro tem um tempo limite de funcionamento (até a gasolina acabar, ele sofrer muito dano, ou alguma peça aleatoriamente dar problema).\n\nDeixo cada mestre livre para optar por como o sistema de transporte funcionará, a parte de \"ESPECIFICAÇÃO\" pode ser alterada ou até mesmo ignorada de acordo com o gosto pessoal \n\nTodas as classes podem dirigir TODOS os veículos, e todas as classes tem -1 no dado para ações com os veículos, para que essa desvantagem cesse, é necessário adiquirir perícia, e caso queria se tornar um especialista em direção, é necessário adiqurir outra perícia posterior.");
        jTextAreaSobre.setWrapStyleWord(true);
        jTextAreaSobre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTextAreaSobre);

        jLabelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg2/Imagens/Carro civil esportivo.jpg"))); // NOI18N
        jLabelImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Descrição: ");

        jTextAreaDesc.setEditable(false);
        jTextAreaDesc.setColumns(20);
        jTextAreaDesc.setLineWrap(true);
        jTextAreaDesc.setRows(5);
        jTextAreaDesc.setWrapStyleWord(true);
        jTextAreaDesc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(jTextAreaDesc);

        jComboBoxListaVeiculos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um veículo", "Carros civis", "Carros civis esportivos", "Hover terrestre", "Hammer de combate", "Carrie truck", "Tank", "Eagle", "Apache" }));
        jComboBoxListaVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxListaVeiculosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxListaVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 74, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxListaVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(271, Short.MAX_VALUE))
        );

        jMenuVoltar.setText("Voltar ao jogo");
        jMenuVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuVoltarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuVoltar);

        jMenuCredito.setText("Créditos");
        jMenuCredito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCreditoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCredito);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_jMenuVoltarMouseClicked

    private void jMenuCreditoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCreditoMouseClicked
        Creditos.creditos();
    }//GEN-LAST:event_jMenuCreditoMouseClicked

    private void jComboBoxListaVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxListaVeiculosActionPerformed
        int opcao = jComboBoxListaVeiculos.getSelectedIndex();

        switch (opcao) {

            case 1:
                Veiculo.getCarroCivil(jTextAreaDesc);
                Veiculo.setImagem(jLabelImagem, opcao);
                break;

            case 2:
                Veiculo.getCarroEsportivo(jTextAreaDesc);
                Veiculo.setImagem(jLabelImagem, opcao);
                break;

            case 3:
                Veiculo.getHoverTerrestre(jTextAreaDesc);
                Veiculo.setImagem(jLabelImagem, opcao);
                break;

            case 4:
                Veiculo.getHammerCombate(jTextAreaDesc);
                Veiculo.setImagem(jLabelImagem, opcao);
                break;

            case 5:
                Veiculo.getCarrieTruck(jTextAreaDesc);
                Veiculo.setImagem(jLabelImagem, opcao);
                break;

            case 6:
                Veiculo.getTank(jTextAreaDesc);
                Veiculo.setImagem(jLabelImagem, opcao);
                break;

            case 7:
                Veiculo.getEagle(jTextAreaDesc);
                Veiculo.setImagem(jLabelImagem, opcao);
                break;

            case 8:
                Veiculo.getApache(jTextAreaDesc);
                Veiculo.setImagem(jLabelImagem, opcao);
                break;

            default:
                Veiculo.cleanDesc(jTextAreaDesc);
                Veiculo.setImagem(jLabelImagem, opcao);

        }
    }//GEN-LAST:event_jComboBoxListaVeiculosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeiculoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxListaVeiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCredito;
    private javax.swing.JMenu jMenuVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaDesc;
    private javax.swing.JTextArea jTextAreaSobre;
    // End of variables declaration//GEN-END:variables
}
