/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpg2.Utilitarios;

import rpg2.Imagens.Imagens;
import rpg2.Sistema.LoadingView;
import rpg2.Ficha.Status;
import rpg2.Sistema.Tela;
import static rpg2.Sistema.PegaData.getLog;

/**
 *
 * @author M4ESTRO
 */
public class DadoView extends javax.swing.JFrame {

    String aux, hora;
    int opcaoTema = 1;
    
    /**
     * Creates new form DadoView
     */
    public DadoView() {
        opcaoTema = LoadingView.getTema();
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        jTextFieldD4 = new javax.swing.JTextField();
        jButtonGirarD4 = new javax.swing.JButton();
        jButtonLimparD4 = new javax.swing.JButton();
        jButtonLimparD6 = new javax.swing.JButton();
        jButtonGirarD6 = new javax.swing.JButton();
        jTextFieldD6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldD10 = new javax.swing.JTextField();
        jButtonD10 = new javax.swing.JButton();
        jButtonLimparD10 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldD12 = new javax.swing.JTextField();
        jButtonD12 = new javax.swing.JButton();
        jButtonLimparD12 = new javax.swing.JButton();
        jButtonLimparD20 = new javax.swing.JButton();
        jButtonD20 = new javax.swing.JButton();
        jTextFieldD20 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jTextFieldNumeroTirado = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldUltimaJogada = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldPenultimaJogada = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldPenultimoNumero = new javax.swing.JTextField();

        setTitle("UTILITÁRIO - Dado");
        setAlwaysOnTop(true);
        setIconImage(Imagens.getIconeTela(4));
        setLocation( Tela.getLargura()/2, Tela.getAltura()/2);
        setMinimumSize(new java.awt.Dimension(332, 308));
        setResizable(false);

        jLabel23.setBackground(new java.awt.Color(0, 0, 153));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        if(opcaoTema == 1){
            jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        }else{
            if(opcaoTema == 2){
                jLabel23.setForeground(new java.awt.Color(145, 0, 160));
            }else{
                jLabel23.setForeground(new java.awt.Color(0, 170, 255));
            }
        }
        jLabel23.setText("D4:");

        jTextFieldD4.setEditable(false);
        jTextFieldD4.setText("0");
        jTextFieldD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldD4ActionPerformed(evt);
            }
        });

        jButtonGirarD4.setText("GIRAR");
        jButtonGirarD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGirarD4ActionPerformed(evt);
            }
        });

        jButtonLimparD4.setText("LIMPAR");
        jButtonLimparD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparD4ActionPerformed(evt);
            }
        });

        jButtonLimparD6.setText("LIMPAR");
        jButtonLimparD6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparD6ActionPerformed(evt);
            }
        });

        jButtonGirarD6.setText("GIRAR");
        jButtonGirarD6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGirarD6ActionPerformed(evt);
            }
        });

        jTextFieldD6.setEditable(false);
        jTextFieldD6.setText("0");

        jLabel5.setBackground(new java.awt.Color(255, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        if(opcaoTema == 1){
            jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        }else{
            if(opcaoTema == 2){
                jLabel5.setForeground(new java.awt.Color(145, 0, 160));
            }else{
                jLabel5.setForeground(new java.awt.Color(0, 170, 255));
            }
        }
        jLabel5.setText("D6:");

        jLabel21.setBackground(new java.awt.Color(255, 0, 0));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        if(opcaoTema == 1){
            jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        }else{
            if(opcaoTema == 2){
                jLabel21.setForeground(new java.awt.Color(145, 0, 160));
            }else{
                jLabel21.setForeground(new java.awt.Color(0, 170, 255));
            }
        }
        jLabel21.setText("D10:");

        jTextFieldD10.setEditable(false);
        jTextFieldD10.setText("0");

        jButtonD10.setText("GIRAR");
        jButtonD10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD10ActionPerformed(evt);
            }
        });

        jButtonLimparD10.setText("LIMPAR");
        jButtonLimparD10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparD10ActionPerformed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(255, 0, 0));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        if(opcaoTema == 1){
            jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        }else{
            if(opcaoTema == 2){
                jLabel22.setForeground(new java.awt.Color(145, 0, 160));
            }else{
                jLabel22.setForeground(new java.awt.Color(0, 170, 255));
            }
        }
        jLabel22.setText("D12:");

        jTextFieldD12.setEditable(false);
        jTextFieldD12.setText("0");

        jButtonD12.setText("GIRAR");
        jButtonD12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD12ActionPerformed(evt);
            }
        });

        jButtonLimparD12.setText("LIMPAR");
        jButtonLimparD12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparD12ActionPerformed(evt);
            }
        });

        jButtonLimparD20.setText("LIMPAR");
        jButtonLimparD20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparD20ActionPerformed(evt);
            }
        });

        jButtonD20.setText("GIRAR");
        jButtonD20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD20ActionPerformed(evt);
            }
        });

        jTextFieldD20.setEditable(false);
        jTextFieldD20.setText("0");

        jLabel24.setBackground(new java.awt.Color(255, 0, 0));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        if(opcaoTema == 1){
            jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        }else{
            if(opcaoTema == 2){
                jLabel24.setForeground(new java.awt.Color(145, 0, 160));
            }else{
                jLabel24.setForeground(new java.awt.Color(0, 170, 255));
            }
        }
        jLabel24.setText("D20");

        jButtonLimpar.setText("LIMPAR TUDO");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jTextFieldNumeroTirado.setEditable(false);
        jTextFieldNumeroTirado.setText(" ");

        jLabel16.setBackground(new java.awt.Color(255, 0, 0));
        if(opcaoTema == 1){
            jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        }else{
            if(opcaoTema == 2){
                jLabel16.setForeground(new java.awt.Color(145, 0, 160));
            }else{
                jLabel16.setForeground(new java.awt.Color(0, 170, 255));
            }
        }
        jLabel16.setText("Número tirado:");

        jTextFieldUltimaJogada.setEditable(false);
        jTextFieldUltimaJogada.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextFieldUltimaJogadaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTextFieldUltimaJogada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUltimaJogadaActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 0, 0));
        if(opcaoTema == 1){
            jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        }else{
            if(opcaoTema == 2){
                jLabel17.setForeground(new java.awt.Color(145, 0, 160));
            }else{
                jLabel17.setForeground(new java.awt.Color(0, 170, 255));
            }
        }
        jLabel17.setText("Última jogada: ");

        jLabel18.setBackground(new java.awt.Color(255, 0, 0));
        if(opcaoTema == 1){
            jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        }else{
            if(opcaoTema == 2){
                jLabel18.setForeground(new java.awt.Color(145, 0, 160));
            }else{
                jLabel18.setForeground(new java.awt.Color(0, 170, 255));
            }
        }
        jLabel18.setText("Penúltima jogada:");

        jTextFieldPenultimaJogada.setEditable(false);
        jTextFieldPenultimaJogada.setText(" ");

        jLabel19.setBackground(new java.awt.Color(255, 0, 0));
        if(opcaoTema == 1){
            jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        }else{
            if(opcaoTema == 2){
                jLabel19.setForeground(new java.awt.Color(145, 0, 160));
            }else{
                jLabel19.setForeground(new java.awt.Color(0, 170, 255));
            }
        }
        jLabel19.setText("Número tirado: ");

        jTextFieldPenultimoNumero.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldD4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldD10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldD6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonGirarD4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonLimparD4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonGirarD6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonLimparD6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonD10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonLimparD10))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldD12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldD20, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonD20)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonLimparD20))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButtonLimparD12)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButtonD12)
                                            .addGap(89, 89, 89)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldUltimaJogada, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNumeroTirado, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPenultimaJogada, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPenultimoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButtonLimpar)
                            .addGap(81, 81, 81)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldD4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonGirarD4)
                        .addComponent(jButtonLimparD4)
                        .addComponent(jLabel23))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldD6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonGirarD6)
                        .addComponent(jButtonLimparD6)
                        .addComponent(jLabel5))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldD10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonD10)
                        .addComponent(jButtonLimparD10)
                        .addComponent(jLabel21))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldD12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonD12)
                        .addComponent(jButtonLimparD12)
                        .addComponent(jLabel22))
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldD20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonD20)
                        .addComponent(jButtonLimparD20)
                        .addComponent(jLabel24))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButtonLimpar)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jTextFieldUltimaJogada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNumeroTirado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jTextFieldPenultimaJogada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(jTextFieldPenultimoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldD4ActionPerformed

    private void jButtonGirarD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGirarD4ActionPerformed

        jTextFieldPenultimaJogada.setText(jTextFieldUltimaJogada.getText());
        jTextFieldPenultimoNumero.setText(jTextFieldNumeroTirado.getText());

        aux = Dados.getDado(4);
        jTextFieldD4.setText(aux);
        hora = getLog();
        jTextFieldUltimaJogada.setText(hora);
        jTextFieldNumeroTirado.setText(aux + " /D4");
    }//GEN-LAST:event_jButtonGirarD4ActionPerformed

    private void jButtonLimparD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparD4ActionPerformed
        Status.limpaCampo(jTextFieldD4);
    }//GEN-LAST:event_jButtonLimparD4ActionPerformed

    private void jButtonLimparD6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparD6ActionPerformed
        Status.limpaCampo(jTextFieldD6);
    }//GEN-LAST:event_jButtonLimparD6ActionPerformed

    private void jButtonGirarD6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGirarD6ActionPerformed
        jTextFieldPenultimaJogada.setText(jTextFieldUltimaJogada.getText());
        jTextFieldPenultimoNumero.setText(jTextFieldNumeroTirado.getText());

        aux = Dados.getDado(6);
        jTextFieldD6.setText(aux);
        hora = getLog();
        jTextFieldUltimaJogada.setText(hora);
        jTextFieldNumeroTirado.setText(aux + " /D6");
    }//GEN-LAST:event_jButtonGirarD6ActionPerformed

    private void jButtonD10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD10ActionPerformed
        jTextFieldPenultimaJogada.setText(jTextFieldUltimaJogada.getText());
        jTextFieldPenultimoNumero.setText(jTextFieldNumeroTirado.getText());

        aux = Dados.getDado(10);
        jTextFieldD10.setText(aux);
        hora = getLog();
        jTextFieldUltimaJogada.setText(hora);
        jTextFieldNumeroTirado.setText(aux + " /D10");
    }//GEN-LAST:event_jButtonD10ActionPerformed

    private void jButtonLimparD10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparD10ActionPerformed
        Status.limpaCampo(jTextFieldD10);
    }//GEN-LAST:event_jButtonLimparD10ActionPerformed

    private void jButtonD12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD12ActionPerformed
        jTextFieldPenultimaJogada.setText(jTextFieldUltimaJogada.getText());
        jTextFieldPenultimoNumero.setText(jTextFieldNumeroTirado.getText());

        aux = Dados.getDado(12);
        jTextFieldD12.setText(aux);
        hora = getLog();
        jTextFieldUltimaJogada.setText(hora);
        jTextFieldNumeroTirado.setText(aux + " /D12");
    }//GEN-LAST:event_jButtonD12ActionPerformed

    private void jButtonLimparD12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparD12ActionPerformed
        Status.limpaCampo(jTextFieldD12);
    }//GEN-LAST:event_jButtonLimparD12ActionPerformed

    private void jButtonLimparD20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparD20ActionPerformed
        Status.limpaCampo(jTextFieldD20);
    }//GEN-LAST:event_jButtonLimparD20ActionPerformed

    private void jButtonD20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD20ActionPerformed
        jTextFieldPenultimaJogada.setText(jTextFieldUltimaJogada.getText());
        jTextFieldPenultimoNumero.setText(jTextFieldNumeroTirado.getText());

        aux = Dados.getDado(20);
        jTextFieldD20.setText(aux);
        hora = getLog();
        jTextFieldUltimaJogada.setText(hora);
        jTextFieldNumeroTirado.setText(aux + " /D20");
    }//GEN-LAST:event_jButtonD20ActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        Status.limpaCampo(jTextFieldD4);
        Status.limpaCampo(jTextFieldD6);
        Status.limpaCampo(jTextFieldD10);
        Status.limpaCampo(jTextFieldD12);
        Status.limpaCampo(jTextFieldD20);
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jTextFieldUltimaJogadaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextFieldUltimaJogadaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUltimaJogadaAncestorAdded

    private void jTextFieldUltimaJogadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUltimaJogadaActionPerformed

    }//GEN-LAST:event_jTextFieldUltimaJogadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DadoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonD10;
    private javax.swing.JButton jButtonD12;
    private javax.swing.JButton jButtonD20;
    private javax.swing.JButton jButtonGirarD4;
    private javax.swing.JButton jButtonGirarD6;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonLimparD10;
    private javax.swing.JButton jButtonLimparD12;
    private javax.swing.JButton jButtonLimparD20;
    private javax.swing.JButton jButtonLimparD4;
    private javax.swing.JButton jButtonLimparD6;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldD10;
    private javax.swing.JTextField jTextFieldD12;
    private javax.swing.JTextField jTextFieldD20;
    private javax.swing.JTextField jTextFieldD4;
    private javax.swing.JTextField jTextFieldD6;
    private javax.swing.JTextField jTextFieldNumeroTirado;
    private javax.swing.JTextField jTextFieldPenultimaJogada;
    private javax.swing.JTextField jTextFieldPenultimoNumero;
    private javax.swing.JTextField jTextFieldUltimaJogada;
    // End of variables declaration//GEN-END:variables
}
