/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpg2.Ficha;

import java.io.Serializable;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import rpg2.Utilitarios.CampoBatalha;
import rpg2.Imagens.Imagens;
import rpg2.Sistema.Tela;
import rpg2.Sistema.UnrealSystemRPGView;

/**
 *
 * @author 2017102465
 */
public class JPanelFicha extends javax.swing.JPanel implements Serializable {

    int classeSelecionada4 = 0;
    JTextField[] nomes = new JTextField[4];
    
    String[] atributos = new String[16];

    String bauDoJogador = "";

    BauPanel bauP = new BauPanel();

    public BauPanel getBauP() {
        return bauP;
    }
    
    public void passaAtributos(){
        int i = 0;
        
        atributos[i] = jTextFieldNivel4.getText();
        i++;
        atributos[i] = jTextFieldVITAtual4.getText();
        i++;
        atributos[i] = jTextFieldFor4.getText() + "+" + jTextFieldForBonus4.getText();
        i++;
        atributos[i] = jTextFieldStm4.getText() + "+" + jTextFieldStmBonus4.getText();
        i++;
        atributos[i] = jTextFieldRes4.getText() + "+" + jTextFieldResBonus4.getText();
        i++;
        atributos[i] = jTextFieldPer4.getText() + "+" + jTextFieldPerBonus4.getText();
        i++;
        atributos[i] = jTextFieldInt4.getText() + "+" + jTextFieldIntBonus4.getText();
    }

    public JPanelFicha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneFicha = new javax.swing.JScrollPane();
        jPanelFicha1 = new javax.swing.JPanel();
        jPanelFichaAtual4 = new javax.swing.JPanel();
        jButtonADDCar4 = new javax.swing.JButton();
        jTextFieldCarBonus4 = new javax.swing.JTextField();
        jTextFieldCar4 = new javax.swing.JTextField();
        jLabel156 = new javax.swing.JLabel();
        jLabel157 = new javax.swing.JLabel();
        jTextFieldPes4 = new javax.swing.JTextField();
        jTextFieldPesBonus4 = new javax.swing.JTextField();
        jButtonADDPes4 = new javax.swing.JButton();
        jButtonADDStm4 = new javax.swing.JButton();
        jTextFieldStmBonus4 = new javax.swing.JTextField();
        jTextFieldStm4 = new javax.swing.JTextField();
        jLabel158 = new javax.swing.JLabel();
        jLabel159 = new javax.swing.JLabel();
        jTextFieldFor4 = new javax.swing.JTextField();
        jTextFieldForBonus4 = new javax.swing.JTextField();
        jButtonADDFor4 = new javax.swing.JButton();
        jButtonAddVIT4 = new javax.swing.JButton();
        jTextFieldVIT4 = new javax.swing.JTextField();
        jLabel160 = new javax.swing.JLabel();
        jLabel162 = new javax.swing.JLabel();
        jLabel163 = new javax.swing.JLabel();
        jLabel164 = new javax.swing.JLabel();
        jTextFieldPer4 = new javax.swing.JTextField();
        jTextFieldInt4 = new javax.swing.JTextField();
        jTextFieldRes4 = new javax.swing.JTextField();
        jTextFieldResBonus4 = new javax.swing.JTextField();
        jButtonADDRes4 = new javax.swing.JButton();
        jButtonADDInt4 = new javax.swing.JButton();
        jTextFieldIntBonus4 = new javax.swing.JTextField();
        jTextFieldPerBonus4 = new javax.swing.JTextField();
        jButtonADDPer4 = new javax.swing.JButton();
        jComboBoxSexo4 = new javax.swing.JComboBox<>();
        jLabel165 = new javax.swing.JLabel();
        jComboBoxClasses4 = new javax.swing.JComboBox<>();
        jLabel166 = new javax.swing.JLabel();
        jLabel167 = new javax.swing.JLabel();
        jTextFieldNome4 = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextAreaFichaNote4 = new javax.swing.JTextArea();
        jLabel168 = new javax.swing.JLabel();
        jLabel169 = new javax.swing.JLabel();
        jTextFieldPontosDisponiveis4 = new javax.swing.JTextField();
        jButtonADDBonus4 = new javax.swing.JButton();
        jLabelMaisOumenosFor4 = new javax.swing.JLabel();
        jLabelMaisOumenosStm4 = new javax.swing.JLabel();
        jLabelMaisOumenosPes4 = new javax.swing.JLabel();
        jLabelMaisOumenosCar4 = new javax.swing.JLabel();
        jLabelMaisOumenosRes4 = new javax.swing.JLabel();
        jLabelMaisOumenosPer4 = new javax.swing.JLabel();
        jLabelMaisOumenosInt4 = new javax.swing.JLabel();
        jButtonRemoverBonus4 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jButtonVantagens4 = new javax.swing.JButton();
        jButtonDesvantagens4 = new javax.swing.JButton();
        jButtonHabilidades4 = new javax.swing.JButton();
        jButtonImagemClasse4 = new javax.swing.JButton();
        jPanelControleFicha4 = new javax.swing.JPanel();
        jTextFieldXP4 = new javax.swing.JTextField();
        jButtonAdicionarVIT4 = new javax.swing.JButton();
        jButtonAdicionarXP4 = new javax.swing.JButton();
        jTextFieldVITAtual4 = new javax.swing.JTextField();
        jLabel172 = new javax.swing.JLabel();
        jTextFieldNivel4 = new javax.swing.JTextField();
        jLabel174 = new javax.swing.JLabel();
        jTextFieldXPPra4 = new javax.swing.JTextField();
        jButtonRemoverVIT4 = new javax.swing.JButton();
        jLabel175 = new javax.swing.JLabel();
        jLabel176 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel189 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jButtonSalvar4 = new javax.swing.JButton();
        jButtonAbrir4 = new javax.swing.JButton();
        jButtonExportar4 = new javax.swing.JButton();
        jButtonNovaFicha4 = new javax.swing.JButton();

        setMinimumSize(Tela.telaFull());
        setPreferredSize(Tela.telaFull());

        jPanelFicha1.setPreferredSize(Tela.telaFull());

        jPanelFichaAtual4.setBackground(new java.awt.Color(153, 153, 153));
        jPanelFichaAtual4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ficha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jButtonADDCar4.setText("+");
        jButtonADDCar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDCar4ActionPerformed(evt);
            }
        });

        jTextFieldCarBonus4.setEditable(false);
        jTextFieldCarBonus4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCarBonus4.setText("0");

        jTextFieldCar4.setEditable(false);
        jTextFieldCar4.setText("0");

        jLabel156.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel156.setForeground(new java.awt.Color(255, 255, 255));
        jLabel156.setText("CAR: ");

        jLabel157.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel157.setForeground(new java.awt.Color(255, 255, 255));
        jLabel157.setText("PES: ");

        jTextFieldPes4.setEditable(false);
        jTextFieldPes4.setText("0");

        jTextFieldPesBonus4.setEditable(false);
        jTextFieldPesBonus4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPesBonus4.setText("0");

        jButtonADDPes4.setText("+");
        jButtonADDPes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDPes4ActionPerformed(evt);
            }
        });

        jButtonADDStm4.setText("+");
        jButtonADDStm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDStm4ActionPerformed(evt);
            }
        });

        jTextFieldStmBonus4.setEditable(false);
        jTextFieldStmBonus4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldStmBonus4.setText("0");

        jTextFieldStm4.setEditable(false);
        jTextFieldStm4.setText("0");

        jLabel158.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel158.setForeground(new java.awt.Color(255, 255, 255));
        jLabel158.setText("STM: ");

        jLabel159.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel159.setForeground(new java.awt.Color(255, 255, 255));
        jLabel159.setText("FOR: ");

        jTextFieldFor4.setEditable(false);
        jTextFieldFor4.setText("0");

        jTextFieldForBonus4.setEditable(false);
        jTextFieldForBonus4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldForBonus4.setText("0");

        jButtonADDFor4.setText("+");
        jButtonADDFor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDFor4ActionPerformed(evt);
            }
        });

        jButtonAddVIT4.setText("+");
        jButtonAddVIT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddVIT4ActionPerformed(evt);
            }
        });

        jTextFieldVIT4.setEditable(false);
        jTextFieldVIT4.setText("100");
        jTextFieldVIT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVIT4ActionPerformed(evt);
            }
        });

        jLabel160.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel160.setForeground(new java.awt.Color(255, 255, 255));
        jLabel160.setText("VIT: ");

        jLabel162.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel162.setForeground(new java.awt.Color(255, 255, 255));
        jLabel162.setText("RES: ");

        jLabel163.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel163.setForeground(new java.awt.Color(255, 255, 255));
        jLabel163.setText("INT: ");

        jLabel164.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel164.setForeground(new java.awt.Color(255, 255, 255));
        jLabel164.setText("PER: ");

        jTextFieldPer4.setEditable(false);
        jTextFieldPer4.setText("0");

        jTextFieldInt4.setEditable(false);
        jTextFieldInt4.setText("0");
        jTextFieldInt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInt4ActionPerformed(evt);
            }
        });

        jTextFieldRes4.setEditable(false);
        jTextFieldRes4.setText("0");

        jTextFieldResBonus4.setEditable(false);
        jTextFieldResBonus4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldResBonus4.setText("0");

        jButtonADDRes4.setText("+");
        jButtonADDRes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDRes4ActionPerformed(evt);
            }
        });

        jButtonADDInt4.setText("+");
        jButtonADDInt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDInt4ActionPerformed(evt);
            }
        });

        jTextFieldIntBonus4.setEditable(false);
        jTextFieldIntBonus4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldIntBonus4.setText("0");

        jTextFieldPerBonus4.setEditable(false);
        jTextFieldPerBonus4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPerBonus4.setText("0");

        jButtonADDPer4.setText("+");
        jButtonADDPer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDPer4ActionPerformed(evt);
            }
        });

        jComboBoxSexo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o sexo", "Masculino", "Feminino" }));

        jLabel165.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel165.setForeground(new java.awt.Color(255, 255, 255));
        jLabel165.setText("Sexo:");

        jComboBoxClasses4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a classe", "Fuzileiro Naval", "Força Policial", "B.H.C", "Hacker", "Químico", "Médico", "Engenheiro" }));
        jComboBoxClasses4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClasses4ActionPerformed(evt);
            }
        });

        jLabel166.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel166.setForeground(new java.awt.Color(255, 255, 255));
        jLabel166.setText("Classe: ");

        jLabel167.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel167.setForeground(new java.awt.Color(255, 255, 255));
        jLabel167.setText("Nome:");

        jTextFieldNome4.setText("");
        jTextFieldNome4.setToolTipText("Insira o nome do personagem (NÃO PODERÁ SER MUDADO DEPOIS)");

        jTextAreaFichaNote4.setColumns(20);
        jTextAreaFichaNote4.setLineWrap(true);
        jTextAreaFichaNote4.setRows(5);
        jTextAreaFichaNote4.setText("Insira anotações sobre o personagem, a sua história, suas perícias e por ai vai...");
        jTextAreaFichaNote4.setToolTipText("Insira anotações extras sobre a ficha. E as perícias adiquiridas");
        jTextAreaFichaNote4.setWrapStyleWord(true);
        jTextAreaFichaNote4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextAreaFichaNote4MouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(jTextAreaFichaNote4);

        jLabel168.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel168.setForeground(new java.awt.Color(255, 255, 255));
        jLabel168.setText("Anotações & Perícias: ");

        jLabel169.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel169.setForeground(new java.awt.Color(255, 255, 255));
        jLabel169.setText("Pontos disponíveis: ");

        jTextFieldPontosDisponiveis4.setEditable(false);
        jTextFieldPontosDisponiveis4.setText("10");

        jButtonADDBonus4.setText("Adicionar Bonus");
        jButtonADDBonus4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDBonus4ActionPerformed(evt);
            }
        });

        jLabelMaisOumenosFor4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMaisOumenosFor4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMaisOumenosFor4.setText(".");

        jLabelMaisOumenosStm4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMaisOumenosStm4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMaisOumenosStm4.setText(".");

        jLabelMaisOumenosPes4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMaisOumenosPes4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMaisOumenosPes4.setText(".");

        jLabelMaisOumenosCar4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMaisOumenosCar4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMaisOumenosCar4.setText(".");

        jLabelMaisOumenosRes4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMaisOumenosRes4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMaisOumenosRes4.setText(".");

        jLabelMaisOumenosPer4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMaisOumenosPer4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMaisOumenosPer4.setText(".");

        jLabelMaisOumenosInt4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMaisOumenosInt4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMaisOumenosInt4.setText(".");

        jButtonRemoverBonus4.setText("Remover Bonus");
        jButtonRemoverBonus4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverBonus4ActionPerformed(evt);
            }
        });

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vereficar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jButtonVantagens4.setText("Vantagens");
        jButtonVantagens4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVantagens4ActionPerformed(evt);
            }
        });

        jButtonDesvantagens4.setText("Desvantagens");
        jButtonDesvantagens4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesvantagens4ActionPerformed(evt);
            }
        });

        jButtonHabilidades4.setText("Habilidades");
        jButtonHabilidades4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabilidades4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVantagens4)
                .addGap(18, 18, 18)
                .addComponent(jButtonDesvantagens4)
                .addGap(18, 18, 18)
                .addComponent(jButtonHabilidades4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVantagens4)
                    .addComponent(jButtonDesvantagens4)
                    .addComponent(jButtonHabilidades4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonImagemClasse4.setText("Foto da classe");
        jButtonImagemClasse4.setEnabled(false);
        jButtonImagemClasse4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImagemClasse4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFichaAtual4Layout = new javax.swing.GroupLayout(jPanelFichaAtual4);
        jPanelFichaAtual4.setLayout(jPanelFichaAtual4Layout);
        jPanelFichaAtual4Layout.setHorizontalGroup(
            jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFichaAtual4Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelFichaAtual4Layout.createSequentialGroup()
                        .addComponent(jTextFieldStmBonus4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonADDStm4))
                    .addGroup(jPanelFichaAtual4Layout.createSequentialGroup()
                        .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelFichaAtual4Layout.createSequentialGroup()
                                .addComponent(jLabel158)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldStm4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMaisOumenosStm4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFichaAtual4Layout.createSequentialGroup()
                                .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel157)
                                    .addComponent(jLabel156))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPes4)
                                    .addComponent(jTextFieldCar4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelMaisOumenosCar4)
                                    .addComponent(jLabelMaisOumenosPes4))))
                        .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFichaAtual4Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jTextFieldPesBonus4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonADDPes4))
                            .addGroup(jPanelFichaAtual4Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jTextFieldCarBonus4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonADDCar4))))
                    .addGroup(jPanelFichaAtual4Layout.createSequentialGroup()
                        .addComponent(jLabel169)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPontosDisponiveis4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFichaAtual4Layout.createSequentialGroup()
                        .addComponent(jLabel160)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldVIT4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAddVIT4))
                    .addGroup(jPanelFichaAtual4Layout.createSequentialGroup()
                        .addComponent(jLabel159)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFor4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMaisOumenosFor4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldForBonus4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonADDFor4)))
                .addGap(67, 67, 67)
                .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFichaAtual4Layout.createSequentialGroup()
                            .addComponent(jTextFieldInt4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelMaisOumenosInt4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldIntBonus4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonADDInt4))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFichaAtual4Layout.createSequentialGroup()
                            .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel163)
                                .addComponent(jLabel162))
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldRes4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelMaisOumenosRes4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldResBonus4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonADDRes4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFichaAtual4Layout.createSequentialGroup()
                        .addComponent(jLabel164)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPer4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMaisOumenosPer4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPerBonus4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonADDPer4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFichaAtual4Layout.createSequentialGroup()
                        .addComponent(jButtonADDBonus4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemoverBonus4)))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFichaAtual4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonImagemClasse4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFichaAtual4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10)
                .addContainerGap())
            .addGroup(jPanelFichaAtual4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel168)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFichaAtual4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelFichaAtual4Layout.createSequentialGroup()
                            .addComponent(jLabel167, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldNome4, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
                        .addGroup(jPanelFichaAtual4Layout.createSequentialGroup()
                            .addComponent(jLabel166)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBoxClasses4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel165)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxSexo4, 0, 302, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanelFichaAtual4Layout.setVerticalGroup(
            jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFichaAtual4Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddVIT4)
                    .addComponent(jTextFieldVIT4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel160))
                .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelFichaAtual4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel164)
                            .addComponent(jTextFieldPerBonus4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonADDPer4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMaisOumenosPer4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonADDRes4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldResBonus4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMaisOumenosRes4)
                            .addComponent(jTextFieldRes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel162))
                        .addGap(19, 19, 19)
                        .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonADDInt4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldIntBonus4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel163)
                                .addComponent(jTextFieldInt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelMaisOumenosInt4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel156)
                            .addComponent(jTextFieldCar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCarBonus4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonADDCar4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFichaAtual4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel159)
                            .addComponent(jTextFieldFor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldForBonus4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMaisOumenosFor4)
                            .addComponent(jButtonADDFor4))
                        .addGap(2, 2, 2)
                        .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel158)
                            .addComponent(jTextFieldStm4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldStmBonus4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonADDStm4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMaisOumenosStm4))
                        .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFichaAtual4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel157)
                                    .addComponent(jTextFieldPes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPesBonus4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonADDPes4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMaisOumenosPes4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFichaAtual4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelMaisOumenosCar4)))))
                .addGap(34, 34, 34)
                .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRemoverBonus4)
                    .addComponent(jTextFieldPontosDisponiveis4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel169)
                    .addComponent(jButtonADDBonus4))
                .addGap(18, 18, 18)
                .addComponent(jLabel168)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonImagemClasse4)))
            .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFichaAtual4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel167)
                        .addComponent(jTextFieldNome4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelFichaAtual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel166)
                        .addComponent(jComboBoxClasses4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel165)
                        .addComponent(jComboBoxSexo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(493, Short.MAX_VALUE)))
        );

        jPanelControleFicha4.setBackground(new java.awt.Color(204, 204, 204));
        jPanelControleFicha4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controle de ficha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelControleFicha4.setForeground(new java.awt.Color(51, 51, 51));

        jTextFieldXP4.setEditable(false);
        jTextFieldXP4.setText("0");

        jButtonAdicionarVIT4.setText("Adicionar VIT");
        jButtonAdicionarVIT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarVIT4ActionPerformed(evt);
            }
        });

        jButtonAdicionarXP4.setText("Adicionar XP");
        jButtonAdicionarXP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarXP4ActionPerformed(evt);
            }
        });

        jTextFieldVITAtual4.setEditable(false);
        jTextFieldVITAtual4.setText("100");

        jLabel172.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel172.setText("VIT Atual");

        jTextFieldNivel4.setEditable(false);
        jTextFieldNivel4.setText("1");

        jLabel174.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel174.setText("/");

        jTextFieldXPPra4.setEditable(false);
        jTextFieldXPPra4.setText("100");
        jTextFieldXPPra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldXPPra4ActionPerformed(evt);
            }
        });

        jButtonRemoverVIT4.setText("Remover VIT");
        jButtonRemoverVIT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverVIT4ActionPerformed(evt);
            }
        });

        jLabel175.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel175.setText("Nível:");

        jLabel176.setText("XP:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel189.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel189.setText("Slot:");

        javax.swing.GroupLayout jPanelControleFicha4Layout = new javax.swing.GroupLayout(jPanelControleFicha4);
        jPanelControleFicha4.setLayout(jPanelControleFicha4Layout);
        jPanelControleFicha4Layout.setHorizontalGroup(
            jPanelControleFicha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControleFicha4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControleFicha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelControleFicha4Layout.createSequentialGroup()
                        .addGroup(jPanelControleFicha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelControleFicha4Layout.createSequentialGroup()
                                .addComponent(jLabel175)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNivel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel176)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldXP4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel174, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldXPPra4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAdicionarXP4))
                            .addComponent(jLabel172)
                            .addGroup(jPanelControleFicha4Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jTextFieldVITAtual4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addGroup(jPanelControleFicha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonRemoverVIT4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControleFicha4Layout.createSequentialGroup()
                                        .addComponent(jButtonAdicionarVIT4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(107, 107, 107))))
                            .addComponent(jLabel189))
                        .addGap(0, 394, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelControleFicha4Layout.setVerticalGroup(
            jPanelControleFicha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControleFicha4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControleFicha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel175)
                    .addComponent(jTextFieldNivel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel176)
                    .addComponent(jTextFieldXP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel174)
                    .addComponent(jTextFieldXPPra4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionarXP4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelControleFicha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel172)
                    .addComponent(jTextFieldVITAtual4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemoverVIT4)
                    .addComponent(jButtonAdicionarVIT4))
                .addGap(18, 18, 18)
                .addComponent(jLabel189)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opções de Ficha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jButtonSalvar4.setText("Salvar");
        jButtonSalvar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvar4ActionPerformed(evt);
            }
        });

        jButtonAbrir4.setText("Abrir");
        jButtonAbrir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrir4ActionPerformed(evt);
            }
        });

        jButtonExportar4.setText("Exportar");
        jButtonExportar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportar4ActionPerformed(evt);
            }
        });

        jButtonNovaFicha4.setText("Nova Ficha");
        jButtonNovaFicha4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaFicha4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNovaFicha4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButtonExportar4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAbrir4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalvar4)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovaFicha4)
                    .addComponent(jButtonExportar4)
                    .addComponent(jButtonAbrir4)
                    .addComponent(jButtonSalvar4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelFicha1Layout = new javax.swing.GroupLayout(jPanelFicha1);
        jPanelFicha1.setLayout(jPanelFicha1Layout);
        jPanelFicha1Layout.setHorizontalGroup(
            jPanelFicha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFicha1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFichaAtual4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFicha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFicha1Layout.createSequentialGroup()
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelControleFicha4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelFicha1Layout.setVerticalGroup(
            jPanelFicha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFicha1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFicha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelControleFicha4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFichaAtual4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jScrollPaneFicha.setViewportView(jPanelFicha1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneFicha, javax.swing.GroupLayout.DEFAULT_SIZE, 1365, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneFicha, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonADDCar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDCar4ActionPerformed
        Status.setStatus(jTextFieldCar4, jTextFieldPontosDisponiveis4);
    }//GEN-LAST:event_jButtonADDCar4ActionPerformed

    private void jButtonADDPes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDPes4ActionPerformed
        Status.setStatus(jTextFieldPes4, jTextFieldPontosDisponiveis4);
    }//GEN-LAST:event_jButtonADDPes4ActionPerformed

    private void jButtonADDStm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDStm4ActionPerformed
        Status.setStatus(jTextFieldStm4, jTextFieldPontosDisponiveis4);
    }//GEN-LAST:event_jButtonADDStm4ActionPerformed

    private void jButtonADDFor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDFor4ActionPerformed
        Status.setStatus(jTextFieldFor4, jTextFieldPontosDisponiveis4);
    }//GEN-LAST:event_jButtonADDFor4ActionPerformed

    private void jButtonAddVIT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddVIT4ActionPerformed
        Status.setVitalidade(jTextFieldVIT4, jTextFieldPontosDisponiveis4);
    }//GEN-LAST:event_jButtonAddVIT4ActionPerformed

    private void jTextFieldVIT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVIT4ActionPerformed
        Status.setStatus(jTextFieldVIT4, jTextFieldPontosDisponiveis4);
    }//GEN-LAST:event_jTextFieldVIT4ActionPerformed

    private void jTextFieldInt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInt4ActionPerformed
        Status.setStatus(jTextFieldInt4, jTextFieldPontosDisponiveis4);
    }//GEN-LAST:event_jTextFieldInt4ActionPerformed

    private void jButtonADDRes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDRes4ActionPerformed
        Status.setStatus(jTextFieldRes4, jTextFieldPontosDisponiveis4);
    }//GEN-LAST:event_jButtonADDRes4ActionPerformed

    private void jButtonADDInt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDInt4ActionPerformed
        Status.setStatus(jTextFieldInt4, jTextFieldPontosDisponiveis4);
    }//GEN-LAST:event_jButtonADDInt4ActionPerformed

    private void jButtonADDPer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDPer4ActionPerformed
        Status.setStatus(jTextFieldPer4, jTextFieldPontosDisponiveis4);
    }//GEN-LAST:event_jButtonADDPer4ActionPerformed

    private void jComboBoxClasses4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClasses4ActionPerformed
        classeSelecionada4 = jComboBoxClasses4.getSelectedIndex();
        jButtonImagemClasse4.setEnabled(true);
    }//GEN-LAST:event_jComboBoxClasses4ActionPerformed

    private void jTextAreaFichaNote4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextAreaFichaNote4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaFichaNote4MouseClicked

    private void jButtonADDBonus4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDBonus4ActionPerformed
        int opcaoInt = Status.opcaoBonus();

        switch (opcaoInt) {
            case -1:
                return;

            case 1:
                Status.addBonus(jTextFieldForBonus4, jLabelMaisOumenosFor4);
                break;

            case 2:
                Status.addBonus(jTextFieldStmBonus4, jLabelMaisOumenosStm4);
                break;

            case 3:
                Status.addBonus(jTextFieldResBonus4, jLabelMaisOumenosRes4);
                break;

            case 4:
                Status.addBonus(jTextFieldPerBonus4, jLabelMaisOumenosPer4);
                break;

            case 5:
                Status.addBonus(jTextFieldIntBonus4, jLabelMaisOumenosInt4);
                break;

            case 6:
                Status.addBonus(jTextFieldPesBonus4, jLabelMaisOumenosPes4);
                break;

            case 7:
                Status.addBonus(jTextFieldCarBonus4, jLabelMaisOumenosCar4);
                break;
        }
    }//GEN-LAST:event_jButtonADDBonus4ActionPerformed

    private void jButtonRemoverBonus4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverBonus4ActionPerformed
        int opcaoInt = Status.opcaoBonus();

        switch (opcaoInt) {
            case -1:
                return;

            case 1:
                Status.removerBonus(jTextFieldForBonus4, jLabelMaisOumenosFor4);
                break;

            case 2:
                Status.removerBonus(jTextFieldStmBonus4, jLabelMaisOumenosStm4);
                break;

            case 3:
                Status.removerBonus(jTextFieldResBonus4, jLabelMaisOumenosRes4);
                break;

            case 4:
                Status.removerBonus(jTextFieldPerBonus4, jLabelMaisOumenosPer4);
                break;

            case 5:
                Status.removerBonus(jTextFieldIntBonus4, jLabelMaisOumenosInt4);
                break;

            case 6:
                Status.removerBonus(jTextFieldPesBonus4, jLabelMaisOumenosPes4);
                break;

            case 7:
                Status.removerBonus(jTextFieldCarBonus4, jLabelMaisOumenosCar4);
                break;
        }
    }//GEN-LAST:event_jButtonRemoverBonus4ActionPerformed

    private void jButtonVantagens4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVantagens4ActionPerformed
        Status.getVantagens(jComboBoxClasses4);
    }//GEN-LAST:event_jButtonVantagens4ActionPerformed

    private void jButtonDesvantagens4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesvantagens4ActionPerformed
        Status.getDesvantagens(jComboBoxClasses4);
    }//GEN-LAST:event_jButtonDesvantagens4ActionPerformed

    private void jButtonHabilidades4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabilidades4ActionPerformed
        Status.getHabilidades(jComboBoxClasses4);
    }//GEN-LAST:event_jButtonHabilidades4ActionPerformed

    private void jButtonImagemClasse4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImagemClasse4ActionPerformed
        classeSelecionada4 = jComboBoxClasses4.getSelectedIndex();
        if (classeSelecionada4 != 0) {
            int sexo = jComboBoxSexo4.getSelectedIndex();
            if (sexo == 1) {
                Imagens.setClasseImagem(classeSelecionada4);
            } else {
                Imagens.setClasseImagemF(classeSelecionada4);
            }

        }
    }//GEN-LAST:event_jButtonImagemClasse4ActionPerformed

    private void jButtonAdicionarVIT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarVIT4ActionPerformed
        Status.addVit(jTextFieldVITAtual4, jTextFieldVIT4, true);
    }//GEN-LAST:event_jButtonAdicionarVIT4ActionPerformed

    private void jButtonAdicionarXP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarXP4ActionPerformed
        Status.addXP(jTextFieldXP4, jTextFieldXPPra4, jTextFieldNivel4, jButtonAdicionarXP4, jTextFieldPontosDisponiveis4);
    }//GEN-LAST:event_jButtonAdicionarXP4ActionPerformed

    private void jTextFieldXPPra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldXPPra4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldXPPra4ActionPerformed

    private void jButtonRemoverVIT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverVIT4ActionPerformed
        ImageIcon imagem = new ImageIcon(ClassLoader.getSystemResource("rpg2/Imagens/Critico.png"));
        int opcaoCritica = JOptionPane.showConfirmDialog(null, "Dano Crítico?", "Dano Crítico?", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, imagem);
        if (opcaoCritica == -1) {
            return;
        }

        //caso seja CRÍTICO
        if (opcaoCritica == 0) {
          //  Status.removerVit(jTextFieldVITAtual4, jTextFieldVIT4, true);
        } else { //caso seja NÃO CRÍTICO
            int defesaAdicional = 0;
            boolean flag = false;
            do {

                try {
                    String def = JOptionPane.showInputDialog(null, "Insira a quantidade da sua defesa adicional: ", "DEFESA ADICIONA", JOptionPane.INFORMATION_MESSAGE);

                    if (def == null) {
                        return;
                    }

                    defesaAdicional = Integer.parseInt(def);
                    flag = false;
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "INSIRA APENAS NÚMEROS! \n" + e.toString());
                    flag = true;
                }

            } while (flag);
            int res = Integer.parseInt(jTextFieldRes4.getText());
            res = res + Integer.parseInt(jTextFieldResBonus4.getText());
            Status.removerVitNaoCritica(jTextFieldVITAtual4, jTextFieldVIT4, res, defesaAdicional);

        }
    }//GEN-LAST:event_jButtonRemoverVIT4ActionPerformed

    private void jButtonSalvar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvar4ActionPerformed

        FichaPersiste ficha = new FichaPersiste();
        if (jTextFieldNome4.equals("")) {
            JOptionPane.showMessageDialog(null, "Impossível salvar ficha sem nome!\n");
            return;
        }

       /* String retorno = ficha.salvar();
        if (retorno.length() <= 28) {
            CampoBatalha.setTodasFichas(jTextFieldNome4,UnrealSystemRPGView.getNumFicha());
            passaAtributos();
            CampoBatalha.setAtributo(atributos, UnrealSystemRPGView.getNumFicha());
            bauP.setJogador(jTextFieldNome4.getText());
            Bau.salvar(jTextFieldNome4, bauP.getBau());
        }   
        
        
        JOptionPane.showMessageDialog(null, retorno);*/

    }//GEN-LAST:event_jButtonSalvar4ActionPerformed

    private void jButtonAbrir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrir4ActionPerformed
        String nome = JOptionPane.showInputDialog("Insira o nome do personagem: ");
        if (nome == null) {
            return;
        }

/*        JPanelFicha ficha = FichaPersiste.abrir(nome, 0);

        if (ficha != null) {
            CampoBatalha.setTodasFichas(jTextFieldNome4,UnrealSystemRPGView.getNumFicha());
            passaAtributos();
            CampoBatalha.setAtributo(atributos, UnrealSystemRPGView.getNumFicha());
            bauP.setJogador(jTextFieldNome4.getText());
            Bau.carregar(jTextFieldNome4, bauP.getBau());
        }*/


    }//GEN-LAST:event_jButtonAbrir4ActionPerformed

    private void jButtonExportar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportar4ActionPerformed

    }//GEN-LAST:event_jButtonExportar4ActionPerformed

    private void jButtonNovaFicha4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaFicha4ActionPerformed
        CampoBatalha.setTodasFichas(jTextFieldNome4,UnrealSystemRPGView.getNumFicha());

        bauP.getBau().setText("");
        bauP.getJogador().setText("");
    }//GEN-LAST:event_jButtonNovaFicha4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonADDBonus4;
    private javax.swing.JButton jButtonADDCar4;
    private javax.swing.JButton jButtonADDFor4;
    private javax.swing.JButton jButtonADDInt4;
    private javax.swing.JButton jButtonADDPer4;
    private javax.swing.JButton jButtonADDPes4;
    private javax.swing.JButton jButtonADDRes4;
    private javax.swing.JButton jButtonADDStm4;
    private javax.swing.JButton jButtonAbrir4;
    private javax.swing.JButton jButtonAddVIT4;
    private javax.swing.JButton jButtonAdicionarVIT4;
    private javax.swing.JButton jButtonAdicionarXP4;
    private javax.swing.JButton jButtonDesvantagens4;
    private javax.swing.JButton jButtonExportar4;
    private javax.swing.JButton jButtonHabilidades4;
    private javax.swing.JButton jButtonImagemClasse4;
    private javax.swing.JButton jButtonNovaFicha4;
    private javax.swing.JButton jButtonRemoverBonus4;
    private javax.swing.JButton jButtonRemoverVIT4;
    private javax.swing.JButton jButtonSalvar4;
    private javax.swing.JButton jButtonVantagens4;
    private javax.swing.JComboBox<String> jComboBoxClasses4;
    private javax.swing.JComboBox<String> jComboBoxSexo4;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel174;
    private javax.swing.JLabel jLabel175;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel189;
    private javax.swing.JLabel jLabelMaisOumenosCar4;
    private javax.swing.JLabel jLabelMaisOumenosFor4;
    private javax.swing.JLabel jLabelMaisOumenosInt4;
    private javax.swing.JLabel jLabelMaisOumenosPer4;
    private javax.swing.JLabel jLabelMaisOumenosPes4;
    private javax.swing.JLabel jLabelMaisOumenosRes4;
    private javax.swing.JLabel jLabelMaisOumenosStm4;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanelControleFicha4;
    private javax.swing.JPanel jPanelFicha1;
    private javax.swing.JPanel jPanelFichaAtual4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPaneFicha;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaFichaNote4;
    private javax.swing.JTextField jTextFieldCar4;
    private javax.swing.JTextField jTextFieldCarBonus4;
    private javax.swing.JTextField jTextFieldFor4;
    private javax.swing.JTextField jTextFieldForBonus4;
    private javax.swing.JTextField jTextFieldInt4;
    private javax.swing.JTextField jTextFieldIntBonus4;
    private javax.swing.JTextField jTextFieldNivel4;
    private javax.swing.JTextField jTextFieldNome4;
    private javax.swing.JTextField jTextFieldPer4;
    private javax.swing.JTextField jTextFieldPerBonus4;
    private javax.swing.JTextField jTextFieldPes4;
    private javax.swing.JTextField jTextFieldPesBonus4;
    private javax.swing.JTextField jTextFieldPontosDisponiveis4;
    private javax.swing.JTextField jTextFieldRes4;
    private javax.swing.JTextField jTextFieldResBonus4;
    private javax.swing.JTextField jTextFieldStm4;
    private javax.swing.JTextField jTextFieldStmBonus4;
    private javax.swing.JTextField jTextFieldVIT4;
    private javax.swing.JTextField jTextFieldVITAtual4;
    private javax.swing.JTextField jTextFieldXP4;
    private javax.swing.JTextField jTextFieldXPPra4;
    // End of variables declaration//GEN-END:variables
}
